package ru.spbstu.pipeline;

public enum RC {
    CODE_SUCCESS,
    CODE_INVALID_ARGUMENT,
    CODE_FAILED_TO_READ,
    CODE_FAILED_TO_WRITE,
    CODE_INVALID_INPUT_STREAM,
    CODE_INVALID_OUTPUT_STREAM,
    CODE_CONFIG_GRAMMAR_ERROR,
    CODE_CONFIG_SEMANTIC_ERROR,
    CODE_FAILED_PIPELINE_CONSTRUCTION,
    CODE_CHUNK_TAKEN,
    CODE_NOTIFICATION_MAX_REACHED;

    private RC() {
    }
}
